### ISSUE TITLE
Add testing framework and write a unit test

### ISSUE THREAD

**Issue by chrissealey** [alanyin0322/star-wars-planet-guide#1]
- Install a JavaScript testing framework
- Write unit tests for https://github.com/alanyin0322/star-wars-planet-guide/blob/master/src/planets/PlanetView.js
   - Ensure that the custom functions are being passed into `PlanetListFilters` correctly and that when called, they correctly set the state on `PlanetView`
   - Ensure `componentDidMount` gets called and retrieves data from your API class

**Comment by alanyin0322** [comment]
@chrissealey 

Hi Chris,

I would just like to let you know that all three pull requests have been finished. I have briefly documented what I have done in the pull request messages and suggested some future improvements. 

Thanks again for taking the time personalising those tasks for me. Very much appreciated.

Have a great weekend and I look forward to hearing from you soon

Kind regards,
Alan

**Comment by chrissealey** [comment]
That’s great. Thanks for letting us know, Alan. We’ll take a look through all of this and get back to you early next week. I hope you have a great weekend too.

**Comment by alanyin0322** [comment]
Thanks Chris!
